inquiries/urls.py
from django.conf.urls import url,include
from django.urls import path
from .views.delete import *
from .views.cancel_invoice import *
from .views.edit import *
from .views.edit_production import *
from .views.display import *
from .views.add_invoice import *
from .views.add_production import *
from .views.add import *
from .views.invoice_detail import *
from .views.add_payment import *
from .views.register_invoice import *
from .views.edit_payment import *
from .views.edit_in_invoices import *
from django.contrib.auth import views as auth_views

urlpatterns =[

    path('',index,name='index'),

    path('accounting/',accounting,name='accounting'),
    path('select_customer/',select_customer,name='select_customer'),
    path('select_producer/',select_producer,name='select_producer'),
    path('order_lookup/',order_lookup,name='order_lookup'),
    path('export_customer_csv/',export_customer_csv,name='export_customer_csv'),
    path('export_producer_csv/',export_producer_csv,name='export_producer_csv'),
    path('export_customer_pdf/',export_customer_pdf,name='export_customer_pdf'),
    path('export_producer_pdf/',export_producer_pdf,name='export_producer_pdf'),
    path('export_invoice_pdf/<pk>/',export_invoice_pdf,name='export_invoice_pdf'),

    path('display_orders/',display_orders,name='display_orders'),
    path('display_brands/',display_brands,name='display_brands'),
    path('display_production/',display_production,name='display_production'),
    path('display_producers/',display_producers,name='display_producers'),
    path('display_customers/',display_customers,name='display_customers'),
    path('display_payments/',display_payments,name='display_payments'),
    path('display_invoices/',display_invoices,name='display_invoices'),
    path('incoming_invoices/',incoming_invoices,name='incoming_invoices'),

    path('invoice_detail/<pk>',invoice_detail,name='invoice_detail'),
    path('edit_in_invoice/<pk>',edit_in_invoice,name='edit_in_invoice'),

    path('add_orders/',add_orders,name='add_orders'),
    path('add_customer/',add_customer,name='add_customer'),
    path('add_producer/',add_producer,name='add_producer'),
    path('add_brands/',add_brands,name='add_brands'),
    path('add_production/',add_production,name='add_production'),
    path('add_payment/',add_payment,name='add_payment'),
    path('add_invoice/',add_invoice,name='add_invoice'),

    path('register_invoice/',register_invoice,name='register_invoice'),

    path('edit_orders/<pk>',edit_orders,name='edit_orders'),
    path('edit_customers/<pk>',edit_customers,name='edit_customers'),
    path('edit_producer/<pk>',edit_producer,name='edit_producer'),
    path('edit_brands/<pk>',edit_brands,name='edit_brands'),

    path('edit_production/<pk>',edit_production,name='edit_production'),

    path('edit_payment/<pk>',edit_payment,name='edit_payment'),

    path('delete_orders/<pk>',delete_orders,name='delete_orders'),
    path('delete_customers/<pk>',delete_customers,name='delete_customers'),
    path('delete_producer/<pk>',delete_producer,name='delete_producer'),
    path('delete_brands/<pk>',delete_brands,name='delete_brands'),
    path('delete_production/<pk>',delete_production,name='delete_production'),
    path('delete_payment/<pk>',delete_payment,name='delete_payment'),
    path('delete_in_invoice/<pk>',delete_in_invoice,name='delete_in_invoice'),
    path('cancel_invoice/<pk>',cancel_invoice,name='cancel_invoice'),

]

order_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inquiries.urls')),
    path('login/', LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', LogoutView.as_view(template_name='Users/logout.html'), name='logout'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('inquiries.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inquiries/models.py
from django.db import models

from django.db import models
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
from .validators import validate_file_size
# Create your models here.

class Customers(models.Model):
    customer_number = models.IntegerField(unique=True, blank =False,)
    name = models.CharField(unique=True, blank =False,max_length=1024,verbose_name= 'Short Name')
    full_name = models.CharField(unique=True, blank =True, max_length=1024,verbose_name= 'Complete Name')
    address = models.CharField(max_length=1024,)
    city = models.CharField(max_length=20,blank =True,)
    delivery_address = models.CharField(max_length=1024,)
    delivery_address_2 = models.CharField(max_length=1024,blank=True,)
    postal_code = models.CharField(max_length=12,)
    country = models.CharField(max_length=8,)
    bonus = models.FloatField(blank =True,default=0,null=True,verbose_name="Bonus")

    def __str__(self):
        return '{}'.format(self.name)

class Producers(models.Model):
    producer_number = models.CharField(unique=True,max_length=200,verbose_name= 'Producer Number')
    name = models.CharField(unique=True, blank =False, max_length=1024,verbose_name= 'Short Name')
    full_name = models.CharField(unique=True, blank =True, max_length=1024,verbose_name= 'Complete Name')
    address = models.CharField(unique=True, blank =False,max_length=1024,verbose_name= 'Address')
    city = models.CharField(max_length=20,blank =True,)
    country = models.CharField(max_length=8,verbose_name= 'Country')


    def __str__(self):
        return '{}'.format(self.name)


class Orders(models.Model):
    order_number = models.CharField(unique=True, blank =False,max_length=8,verbose_name="Order Number")
    article = models.CharField(max_length=12,blank =False,verbose_name="Article")
    date = models.DateField( blank =False,verbose_name="Signed Date",)
    order_due_date = models.DateField(blank =False,verbose_name="Delivery Date")
    order_pcs = models.IntegerField(blank =False,verbose_name="Total Pieces")
    customer = models.ForeignKey('Customers',null=True, on_delete = models.SET_NULL,)
    price = models.FloatField(verbose_name="Price")
    brand = models.ForeignKey('Brands',null=True, on_delete = models.SET_NULL)
    in_production = models.BooleanField(default=False)
    description = models.CharField(max_length=120,blank =True,null=True,verbose_name="Description")

    def __str__(self):
        return '{}'.format(self.order_number)

class Productions(models.Model):
    order = models.ForeignKey('Orders',on_delete=models.CASCADE,verbose_name="Order Number")
    production_due_date = models.DateField(null=True,verbose_name="Confirmed Date")
    load_date = models.DateField(blank=True,null=True,verbose_name="Load Date")
    producer = models.ForeignKey('Producers',null=True,on_delete=models.SET_NULL)
    production_load_count = models.IntegerField(blank =False,null=True,validators=[MinValueValidator(1)],verbose_name="Amount(pcs)")
    production_price = models.FloatField(blank =False,null=True,verbose_name="Production Price")
    bonus = models.FloatField(blank=True,null=True, default=4,)
    assigned_in_invoice = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    in_invoice = models.ForeignKey('IncomingInvoices',blank=True,null=True,on_delete = models.SET_NULL)
    invoice = models.ForeignKey('Invoices',blank=True,null=True,on_delete = models.CASCADE)

    def __str__(self):
        return '{}'.format(self.order)

class Calculations(models.Model):
    order = models.ForeignKey('Orders',on_delete=models.CASCADE,verbose_name="Order Number", null = True)
    production = models.ForeignKey('Productions',on_delete=models.CASCADE,verbose_name="Production", null=True)
    date = models.DateField(blank=False,null=True,verbose_name="Loaded Date")
    sale_neto = models.FloatField(blank =True,verbose_name="Neto Sum")
    sale_vat = models.FloatField(blank =True,verbose_name="Total VAT")
    sale_gross = models.FloatField(blank =True,verbose_name="Gross Sum")
    buy_neto = models.FloatField(blank =True,default=0,verbose_name="Neto Sum")
    buy_bonus = models.FloatField(blank =True,default=0,verbose_name="Total Bonus")
    buy_gross = models.FloatField(blank =True,default=0,verbose_name="Buy Gross")
    profit = models.FloatField(blank =True,default=0,verbose_name="Profit")
    days_late = models.IntegerField(blank =True,default=0,verbose_name="Late Delivery")
    amount_difference = models.IntegerField(blank =True,verbose_name="Amount Difference")
    description = models.CharField(max_length=20,blank=True,null=True,verbose_name="Item Description")

    def __str__(self):
        return '{}'.format(self.order)

class Brands(models.Model):
    brand_name = models.CharField(unique=True, blank =False,max_length=200,verbose_name= 'Brand Name')
    customer = models.ForeignKey('Customers',on_delete=models.CASCADE,verbose_name= 'Customer ID')

    def __str__(self):
        return '{} - {}'.format(self.brand_name,self.customer)

class Payments(models.Model):
    PAYMENT_TYPE = [
        ('In', 'Incoming'),
        ('Out', 'Outgoing'),
    ]
    amount = models.FloatField(blank=False,default=0,verbose_name="Amount")
    date = models.DateField(default=datetime.datetime.now(), blank =False,verbose_name="Date")
    customer = models.ForeignKey('Customers',blank=True,null=True,on_delete = models.SET_NULL)
    producer = models.ForeignKey('Producers',blank=True,null=True,on_delete = models.SET_NULL)
    payment_type = models.TextField(blank =False,null=True, max_length=1024,choices= PAYMENT_TYPE)
    description = models.CharField(max_length=120,blank=True,null=True,verbose_name="Description")

    def __str__(self):
        return '{} - {} - {}'.format(self.date,self.amount, self.payment_type)

class Invoices(models.Model):
    INVOICE_TYPE = [
        ('Invoice', 'Invoice'),
        ('Reklamation', 'Reklamation'),
        ('Diverse','Diverse'),
    ]
    invoice_number = models.CharField(max_length=120,unique=True, blank =False,verbose_name="Inovice Number")
    invoice_date = models.DateField(blank =False,verbose_name="Invoice Date")
    customer = models.ForeignKey('Customers',blank=True,null=True,on_delete = models.SET_NULL)
    producer = models.ForeignKey('Producers',blank=True,null=True,on_delete = models.SET_NULL)
    invoice_type = models.CharField(blank =False, max_length=1024,choices=INVOICE_TYPE)
    payment = models.ForeignKey('Payments',blank=True,null=True,on_delete=models.SET_NULL,verbose_name="Payment")
    cancelled = models.BooleanField(default=False)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.invoice_number)

class IncomingInvoices(models.Model):
    INVOICE_TYPE = [
        ('Invoice', 'Invoice'),
        ('Reklamation', 'Reklamation'),
        ('Diverse','Diverse')
    ]
    invoice_number = models.CharField(max_length=120,blank =False,verbose_name="Inovice Number")
    invoice_date = models.DateField(blank =False,verbose_name="Invoice Date")
    customer = models.ForeignKey('Customers',blank=True,null=True,on_delete = models.SET_NULL)
    producer = models.ForeignKey('Producers',blank=True,null=True,on_delete = models.SET_NULL)
    invoice_type = models.CharField(blank =False,null=True, max_length=1024,choices=INVOICE_TYPE)
    payment = models.ForeignKey('Payments',blank=True,null=True,on_delete=models.SET_NULL,verbose_name="Payment")
    closed = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.invoice_number)

class Documents(models.Model):
    invoice = models.ForeignKey('IncomingInvoices',blank=True,null=True,on_delete=models.CASCADE,verbose_name="Invoice")
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(validators=[validate_file_size])
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.document)

    def delete(self,*args, **kwargs):
        self.document.delete()
        super().delete(*args, **kwargs)

class Items(models.Model):
    name = models.CharField(blank=True,null=True, max_length=120,verbose_name="Item name")
    description = models.CharField(blank=True,null=True, max_length=120,verbose_name="Item description")
    customer = models.ForeignKey('Customers',blank=True,null=True,on_delete = models.SET_NULL)
    producer = models.ForeignKey('Producers',blank=True,null=True,on_delete = models.SET_NULL)
    price = models.FloatField(blank=True,null=True,verbose_name="Price")
    amount = models.IntegerField(blank=True,null=True,verbose_name="Amount")
    invoice = models.ForeignKey('Invoices',blank=True,null=True,on_delete = models.CASCADE)
    total = models.FloatField(blank=True,null=True,verbose_name="Total")
    vat = models.FloatField(blank=True,null=True,verbose_name="Vat")
    total_sum = models.FloatField(blank=True,null=True,verbose_name="Total Sum")

    def __str__(self):
        return '{}-{}-{}'.format(self.invoice.invoice_date,self.name,self.invoice)

inquiries/views.py
from django.shortcuts import render

# Create your views here.

inquiries/views/add.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from inquiries.models import *
from inquiries.forms import *
from inquiries.views.edit import edit_info
from inquiries.functions import create_calculation,add_calculation
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required
def is_form_valid(request, form):
    is_valid = True

    if isinstance(form, BrandsForm):
        new_brand_name = form['brand_name'].data
        already_existing_brand = Brands.objects.filter(brand_name=new_brand_name)

        if already_existing_brand:
            is_valid = False
            messages.warning(request, "Brand name already exists")

    if isinstance(form, OrdersForm):
        date_obj = datetime.datetime.strptime(form['date'].data, '%Y-%m-%d')
        due_date_obj = datetime.datetime.strptime(form['order_due_date'].data, '%Y-%m-%d')
        order_price = form['price'].data
        p = float(order_price)
        order = form['order_number'].data
        order_pcs = form['order_pcs'].data
        if int(order_pcs) <0:
            is_valid = False
            messages.warning(request, "Total Pieces cannot be a negative number!")
        if Orders.objects.filter(order_number=order):
            is_valid = False
            messages.warning(request, "Order number should be unique!")
        if p < 0:
            is_valid = False
            messages.warning(request, "Price cannot be negative!")
        if date_obj > due_date_obj:
            is_valid = False
            messages.warning(request, "Please check the delivery date")
        b = form['brand'].data
        c = form['customer'].data
        if int(c) != (Brands.objects.get(pk=b)).customer.pk:
            is_valid = False
            messages.warning(request, "Please check customer and brand")

    return is_valid

@login_required
def add_new(request, cls, context,template):
    form = cls()
    if  request.method =='POST':
        form = cls(request.POST)
        if (context == 'Order') and not is_form_valid(request, form):
            return render(request,'add_info.html',{'form':form,'template':template})
        if (context=='Brand') and not is_form_valid(request, form):
            return render(request,'add_info.html',{'form':form,'template':template})

        if form.is_valid():
            form.save()
        messages.success(request, context + " succesfully created")
        return redirect(template)
    else:
        form = cls()
        return render(request,'add_info.html',{'form':form, 'title': context,'template':template})
@login_required
def add_orders(request):
    return add_new(request, OrdersForm, 'Order','display_orders')
@login_required
def add_customer(request):
    return add_new(request, CustomersForm, 'Customer','display_customers')
@login_required
def add_producer(request):
    return add_new(request, ProducerForm, 'Producer','display_producers')
@login_required
def add_brands(request):
    return add_new(request, BrandsForm, 'Brand','display_brands')

inquiries/templates/add_info.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<br>
<br>
  {% if messages %}
          {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
                  {{ message }}
          </div>
          {% endfor %}
  {% endif %}
  <div class="shadow p-3 mb-5 bg-white rounded">
  <div class="row">
    <a href="{% url template %}" class="navigation" role="button" style="font-size:12px">Back</a>
  </div>
  <br>
      <form class="text-center" method="POST">
          {% csrf_token %}
          <div class="shadow p-3 mb-5 bg-white rounded">
            <h5 class="header-title">Adding {{title}}</h5> 
          </div>
          <div class="shadow p-3 mb-5 bg-white rounded">
              {% for field in form %}
              <div class="form-group row">
                  <label for="id_{{field.name}}" class="col-3 col-form-label">{{field.label}}</label>
                  <div class="col-6">
                    {{ field}}
                  </div>
              </div>
              {% endfor %}
              <div class="form-group row">
                <div class="offset-sm-2 col-sm-6">
                  <button type="submit" class="navigation-create">Save</button>
                </div>
              </div>
          </div>
      </form>
</div>
<script>
$('#id_customer').change(function(){
  const client = $('#id_customer option:selected');
  $('#id_brand').children().each(function() {
    $(this).css('display', '');
  });
  $('#id_brand').val([]);
  if(!client.val()){
    return
  }
  $('#id_brand').children().each(function() {
    let option = $(this);
    if (!option.text().includes(client.text())){
      option.css('display', 'none');
    }
  });
});
</script>
{% endblock%}

inquiries/templates/add_production.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
<br>
<div class="shadow p-3 mb-5 bg-white rounded">
    {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                    {{ message }}
            </div>
            {% endfor %}
    {% endif %}
    <div class="row">
      <a href="{% url 'display_production' %}" class="navigation" role="button" style="font-size:12px">Back</a>
    </div>
    <br>
      <form class="text-center" method="POST">
          {% csrf_token %}
          <div class="shadow p-3 mb-5 bg-white rounded">
            <h5>Adding Production</h5>
          </div>
          <div class="shadow p-3 mb-5 bg-white rounded">
              {% for field in form %}
              <div class="form-group row">
                  <label for="id_{{field.name}}" class="col-3 col-form-label">{{field.label}}</label>
                  <div class="col-6">
                    {{field|attr:"class:form-control"}}
                  </div>
              </div>
              {% endfor %}
              <div class="form-group row">
                <div class="offset-sm-2 col-sm-6">
                  <button type="submit" class="navigation-create">Save</button>
                </div>
              </div>
          </div>
      </form>
  </div>
</div>
{% endblock%}

inquiries/templates/confirm_cancelling.html
{% extends 'base.html' %}

{% block body %}
<br>
<br>
  <div class="card shadow p-3 mb-5 bg-white rounded">
    <form method="POST">

        {% csrf_token %}
        <div class="card shadow p-3 mb-5 bg-white rounded second">
          Cancelling "{{Model}}"
        </div>
        <h4>Are you sure you want to cancel this Invoice?</h4>
        <button class="delete-druck" type="submit">Yes Cancel!</button>
        <a class="navigation" href="{% url 'display_invoices'  %}">Abort</a>
    </form>
  </div>
<style>
  .card.shadow.p-3.mb-5.bg-white.rounded {
    min-width: 425px;
  }
  .card.shadow.p-3.mb-5.bg-white.rounded.second{
    min-width: 350px;
    max-width: auto;
  } 
</style>
{% endblock%}

inquiries/templates/register_invoice.html
{% extends 'base.html' %}
{% block body %}
<br>
<br>
<div class="shadow p-3 mb-5 bg-white rounded">
    {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                    {{ message }}
            </div>
            {% endfor %}
    {% endif %}  
    <div class="row">
      <a href="{% url 'incoming_invoices' %}" class="navigation" role="button" style="font-size:12px">Back</a>
    </div>
    <br>
        <form class="text-center" method="POST" action="{% url 'register_invoice' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="shadow p-3 mb-5 bg-white rounded">
                <h5>Register Invoice</h5>
            </div>
            <div class="shadow p-3 mb-5 bg-white rounded">
                {% for field in form %}
                <div class="form-group row">
                    <label for="id_{{field.name}}" class="col-3 col-form-label">{{field.label}}</label>
                    <div class="col-6">
                        {{field}}
                    </div>
                </div>
                {% endfor %}
                <div class="form-group row">
                    <label for="producers" class="col-3 col-form-label">Producer</label>
                      <div class="col-6">
                        <select id="producer-list" class="form-control" name="producer">
                          {% for option in producers_list %}
                            <option value="" disabled selected hidden>Select Producer</option>
                            <option value="{{ option.pk }}">{{ option }}</option>
                          {% endfor %}
                        </select>
                      </div>
                      <div class="col-1">
                        <button id="reset_options_producer" class="btn btn-danger btn-circle" name="button">X</button>
                      </div>
                  </div>
                  <div class="form-group row">
                    <label for="customers" class="col-3 col-form-label">Customer</label>
                      <div class="col-6">
                        <select id="customer-list" class="form-control" name="customer">
                          {% for option in customers_list %}
                            <option value="" disabled selected hidden>Select Customer</option>
                            <option value="{{ option.pk }}">{{ option }}</option>
                          {% endfor %}
                        </select>
                      </div>
                      <div class="col-1">
                        <button id="reset_options_customer" class="btn btn-danger btn-circle" name="button">X</button>
                      </div>
                  </div>
                  <div class="form-group row">
                    <label for="description" class="col-3 col-form-label">Description</label>
                    <div class="col-6">
                      <input
                        id="description"
                        type="text"
                        class="form-control mr-sm-2"
                        placeholder="Enter Description"
                        aria-label="Description"
                        name='description'>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="documents" class="col-3 col-form-label">Upload Files</label>
                        <div class="col-6">
                            <input type="file" name="documents" multiple/>
                        </div>
                  </div>
                  <div class="form-group row productions">
                    <label for="productions[]" class="col-3 col-form-label">Select Orders</label>
                      <div class="col-6">
                        <select id="production-list-select2" class="form-control" name="productions[]" multiple="multiple">
                          {% for option in production_list %}
                            <option value="{{ option.pk }}">{{ option }}</option>
                          {% endfor %}
                        </select>
                      </div>
                  </div>
                  <br>
                <div class="form-group row">
                    <div class="offset-sm-2 col-sm-6">
                      <button type="submit" class="navigation-create" name="button">Save</button>
                    </div>
                </div>    
            </div>
        </form>
    </div>
</div>
<script>
  $(document).ready(function() {
      $('#production-list-select2').select2({
        class: "form-control",
        theme: 'bootstrap4',
      });
    });

  $('#id_invoice_type').change(function(){
    const type = $(this).children("option:selected").val();
    if (type == 'Invoice'){
      $('#reset_options_producer').hide();
      $('#reset_options_customer').hide();
      $('#customer-list').css('opacity', '0.6');
      $('#customer-list').css("pointer-events","none");
      $('#producer-list').css('opacity', '1');
      $('#producer-list').css("pointer-events","auto");
      $('div.form-group.row.productions').show();
      $('label[for="productions[]"]').show();
      $('#production-list-select2').next(".select2-container").show();
    }
    
    else if (type == 'Reklamation') {
      $('#reset_options_producer').hide();
      $('#reset_options_customer').hide();
      $('#customer-list').css('opacity', '1');
      $('#customer-list').css("pointer-events","auto");
      $('#producer-list').css('opacity', '0.6');
      $('#producer-list').css("pointer-events","none");
      $('div.form-group.row.productions').hide();
      $('label[for="productions[]"]').hide();
      $('#production-list-select2').next(".select2-container").hide();
      }
    else {
      $('#customer-list').css('opacity', '1');
      $('#customer-list').css("pointer-events","auto");
      $('#producer-list').css('opacity', '1');
      $('#producer-list').css("pointer-events","auto");
      $('div.form-group.row.productions').hide();
      $('label[for="productions[]"]').hide();
      $('#production-list-select2').next(".select2-container").hide();
    }
  });

  $('#customer-list').change(function(){
    $('#producer-list').css('opacity', '0.6');
    $('#producer-list').css("pointer-events","none");
    $('#reset_options_customer').show();
  });
  $('#producer-list').change(function(){
    $('#customer-list').css('opacity', '0.6');
    $('#customer-list').css("pointer-events","none");
    $('#reset_options_producer').show();
  });
  $('#reset_options_customer').click(function(){
    event.preventDefault()
    const type = $('#id_invoice_type').children("option:selected").val(); 
    if (type == 'Reklamation'){
      $('#customer-list').val('');
      $('#customer-list').css('opacity', '1');
      $('#customer-list').css("pointer-events","auto");
      $('#producer-list').css('opacity', '0.6');
      $('#producer-list').css("pointer-events","none");
      $('#reset_options_customer').hide();
    } 
    else{
      $('#customer-list').val('');
      $('#customer-list').css('opacity', '1');
      $('#customer-list').css("pointer-events","auto");
      $('#producer-list').css('opacity', '1');
      $('#producer-list').css("pointer-events","auto");
      $('#reset_options_customer').hide();
    }
  });
  $('#reset_options_producer').click(function(){
    event.preventDefault()
    $('#producer-list').val('');
    $('#customer-list').css('opacity', '1');
    $('#customer-list').css("pointer-events","auto");
    $('#producer-list').css('opacity', '1');
    $('#producer-list').css("pointer-events","auto");
    $('#reset_options_producer').hide();
  });
  $(document).ready(function() {
    $('#reset_options_producer').hide();
    $('#reset_options_customer').hide();
  });

    $(document).ready(function() {
      const type = $('#id_invoice_type').children("option:selected").val();
      if (type == 'Invoice'){
      $('#reset_options_producer').hide();
      $('#reset_options_customer').hide();
      $('#customer-list').css('opacity', '0.6');
      $('#customer-list').css("pointer-events","none");
      $('#producer-list').css('opacity', '1');
      $('#producer-list').css("pointer-events","auto");
      $('div.form-group.row.productions').show();
      $('label[for="productions[]"]').show();
      $('#production-list-select2').next(".select2-container").show();
    }
    
    else if (type == 'Reklamation') {
      $('#reset_options_producer').hide();
      $('#reset_options_customer').hide();
      $('#customer-list').css('opacity', '1');
      $('#customer-list').css("pointer-events","auto");
      $('#producer-list').css('opacity', '0.6');
      $('#producer-list').css("pointer-events","none");
      $('div.form-group.row.productions').hide();
      $('label[for="productions[]"]').hide();
      $('#production-list-select2').next(".select2-container").hide();
      }
    else {
      $('#customer-list').css('opacity', '1');
      $('#customer-list').css("pointer-events","auto");
      $('#producer-list').css('opacity', '1');
      $('#producer-list').css("pointer-events","auto");
      $('div.form-group.row.productions').hide();
      $('label[for="productions[]"]').hide();
      $('#production-list-select2').next(".select2-container").hide();
    }
    });
</script>
{% endblock%}